### ISSUE TITLE
Question: Why does running build.cmd ask me to install .NET 3.5?

### ISSUE THREAD

**Issue by castever** [jeffogata/contosouniversity2016#2]
While running build.cmd I get a popup asking me to install .NET 3.5.

**Comment by jeffogata** [comment]
I was using the most recent RoundhousE build from their downloads page.  That targeted .NET 3.5, so I replaced it with the latest build from their build server (targets .NET 4.5).  I also updated the ASP.NET 5 references from 1.0.0-rc1-final to 1.0.0-rc1-update1.

Please let me know if that does not resolve the issue (I have not tested it on a machine that doesn't have .NET 3.5 installed).
